### ISSUE TITLE
Call to undefined function MarkdownExtended() 

### ISSUE THREAD

**Issue by X3msnake** [PhileCMS/phileMarkdownExtraExtended#5]
Trying to install the plugin, but it's throwing an error.

Any light on why is this showing up?

////
Error

Call to undefined function Phile\Plugin\Phile\MarkdownExtraExtended\MarkdownExtended() [1]  
triggered in file /media/2ce97fcd-24d9-47e8-87f1-f4eea6762d8c/webserver/public_html/plugins/phile/markdownExtraExtended/Classes/Parser.php on line 10.

/media/2ce97fcd-24d9-47e8-87f1-f4eea6762d8c/webserver/public_html/plugins/phile/markdownExtraExtended/Classes/Parser.php:
00005: use Phile\ServiceLocator\ParserInterface; 
00006:  
00007: class Parser implements ParserInterface { 
00008:   // overload parse with the MarkdownExtra parser 
00009:   public function parse($data) { 
00010:     return MarkdownExtended($data); 
00011:   } 
00012: } 
00013:

**Comment by Schlaefer** [comment]
Hi, thanks for the feedback. Alas nobody is maintaining this repository at the moment.

I close this issue as I mark this repository as abandoned and archived.
